# pip install numpy

In [1]:
import numpy as np # alias conventional

array -> valorile sunt de acelasi tip

lista -> valorile pot fi de tipuri diferite

In [3]:
print(np.__doc__)


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularly 

In [4]:
lista = [120, 230, 30, 30]
type(lista)

list

In [5]:
arr = np.array([120, 230, 30, 30])
type(arr)

numpy.ndarray

In [7]:
arr[0], arr[-1]

(np.int64(120), np.int64(30))

In [8]:
arr.dtype

dtype('int64')

In [10]:
arr = np.array([120, 230, 30, 30.32])
arr, arr.dtype

(array([120.  , 230.  ,  30.  ,  30.32]), dtype('float64'))

In [14]:
for i in range(17):
    print("i=", i, " in baza 2:", bin(i))

i= 0  in baza 2: 0b0
i= 1  in baza 2: 0b1
i= 2  in baza 2: 0b10
i= 3  in baza 2: 0b11
i= 4  in baza 2: 0b100
i= 5  in baza 2: 0b101
i= 6  in baza 2: 0b110
i= 7  in baza 2: 0b111
i= 8  in baza 2: 0b1000
i= 9  in baza 2: 0b1001
i= 10  in baza 2: 0b1010
i= 11  in baza 2: 0b1011
i= 12  in baza 2: 0b1100
i= 13  in baza 2: 0b1101
i= 14  in baza 2: 0b1110
i= 15  in baza 2: 0b1111
i= 16  in baza 2: 0b10000


In [18]:
2 ** 4

16

In [20]:
2 ** 8 - 1

255

In [17]:
arr = np.array([1, 2, 3],dtype=np.int8)
arr.dtype

dtype('int8')

# UINT8 - de la 0 la 255 (2 ** 8 - 1)

In [22]:
arr = np.array([255, 2, 3],dtype=np.uint8)
arr.dtype

dtype('uint8')

In [23]:
arr = np.array([256, 2, 3],dtype=np.uint8)
arr.dtype

OverflowError: Python integer 256 out of bounds for uint8

# INT8 - de la -128 la 127 (- 2 ** 7 la 2 ** 7 - 1)

In [24]:
arr = np.array([-128, 127, 3],dtype=np.int8)
arr.dtype

dtype('int8')

In [25]:
arr = np.array([-128, 127, 3],dtype=np.int8)
arr.dtype

OverflowError: Python integer -129 out of bounds for int8

In [26]:
arr = np.array([-128, 128, 3],dtype=np.int8)
arr.dtype

OverflowError: Python integer 128 out of bounds for int8

## Fast mathematical operations

# 1. Mapare

In [27]:
arr = np.array([11, 22, 33, 44, 55])
arr

array([11, 22, 33, 44, 55])

In [28]:
arr + 2

array([13, 24, 35, 46, 57])

In [29]:
arr * 3

array([ 33,  66,  99, 132, 165])

In [30]:
arr + arr

array([ 22,  44,  66,  88, 110])

In [31]:
arr - arr

array([0, 0, 0, 0, 0])

# 2. Filtrare

In [32]:
arr = np.array([11, 22, 33, 44, 55])
arr > 22

array([False, False,  True,  True,  True])

In [33]:
arr[arr > 22]

array([33, 44, 55])

In [37]:
arr = np.array([11, 22, 33, 44, 55, 66, 77, 88, 99, 100])

arr[(arr > 22) & (arr < 88)] # AND -> 2 conditii simulan

array([33, 44, 55, 66, 77])

In [38]:
arr = np.array([11, 22, 33, 44, 55, 66, 77, 88, 99, 100])

arr[(arr <= 22) | (arr >= 88)] # OR -> 2 conditii alternativ

array([ 11,  22,  88,  99, 100])

In [39]:
arr = np.array([11, 22, 33, 44, 55, 66, 77, 88, 99, 100])

conditia1 = (arr <= 22) 
conditia2 = (arr >= 88)

arr[conditia1 | conditia2 ] # OR -> 2 conditii alternativ

array([ 11,  22,  88,  99, 100])

# 3. Reduce

In [40]:
arr = np.array([11, 22, 33, 44, 55, 66, 77, 88, 99, 100])
arr.max()

np.int64(100)

In [41]:
arr.min()

np.int64(11)

In [42]:
arr.sum()

np.int64(595)

In [43]:
arr.mean()

np.float64(59.5)

In [44]:
arr.size

10

In [45]:
arr.shape

(10,)

In [46]:
arr = np.array([ [11, 22, 33, 44, 55], [66, 77, 88, 99, 100]])
arr.shape

(2, 5)

In [48]:
arr = np.array([ [11, 22, 33, 44, 55], [66, 77, 88, 99, 100]])
arr.shape

(2, 5)