In [1]:
import numpy as np

In [2]:
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [3]:
np.array([1, 2, 3, 4, 5, True])

array([1, 2, 3, 4, 5, 1])

In [4]:
np.array([1, 2, 3, 4, 5, True, 23.])

array([ 1.,  2.,  3.,  4.,  5.,  1., 23.])

In [5]:
np.array([1, 2, 3, 4, 5, True, 23., "hello"])

array(['1', '2', '3', '4', '5', 'True', '23.0', 'hello'], dtype='<U32')

In [6]:
np.array(range(100))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [7]:
np.arange(100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [9]:
np.arange(100,dtype=np.float64)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38.,
       39., 40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50., 51.,
       52., 53., 54., 55., 56., 57., 58., 59., 60., 61., 62., 63., 64.,
       65., 66., 67., 68., 69., 70., 71., 72., 73., 74., 75., 76., 77.,
       78., 79., 80., 81., 82., 83., 84., 85., 86., 87., 88., 89., 90.,
       91., 92., 93., 94., 95., 96., 97., 98., 99.])

In [17]:
np.random.random()

0.8663655845999942

In [18]:
np.random.random(10)

array([0.8051091 , 0.74132842, 0.81563007, 0.92735267, 0.2151077 ,
       0.10115064, 0.2028558 , 0.1281489 , 0.31715345, 0.00718572])

In [19]:
np.random.random((2, 3))

array([[0.4792648 , 0.11336641, 0.72886423],
       [0.23587685, 0.10393266, 0.64918848]])

In [24]:
np.random.randint(1, 100, (3, 2))

array([[72, 65],
       [57, 26],
       [38, 77]])

In [26]:
np.linspace(0, 100, 3)

array([  0.,  50., 100.])

In [27]:
np.linspace(0, 100, 4)

array([  0.        ,  33.33333333,  66.66666667, 100.        ])

In [28]:
np.linspace(0, 100, 10)

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])